username:   Automationbot.us
password:   spicypancakes1
site_url:   https://etap-cdev-fh.blackbaudhosting.com/prod/
image_path: /home/ubuntu/qa-etap-main/misc/cart_image.jpg
headless_enabled: true
complete_import_path: /home/ubuntu/qa-etap-main/misc/import_a.csv
incomplete_import_path: /home/ubuntu/qa-etap-main/misc/import_b.csv
site_url_knight_rider: https://etap-cdev-kr.blackbaudhosting.com/prod/
site_url_mobile: https://etap-cdev-fh.blackbaudhosting.com/mobile/Login.jsp
username_kr:   automationbot.lucene.us
password_kr:   spicypancakes1
