username:   Automationbot.mdilts.us
password:   spicypancakes1
site_url:   https://etap-cdev-fh.blackbaudhosting.com/prod/
image_path: /home/trey/qa-etap-main/misc/cart_image.jpg
headless_enabled: false
complete_import_path: /home/trey/qa-etap-main/misc/import_a.csv
incomplete_import_path: /home/trey/qa-etap-main/misc/import_b.csv
