username:   automationbot.lmoore.us
#username:   Automationbot.us
password:   spicypancakes1
site_url:   https://etap-cdev-fh.blackbaudhosting.com/prod/
image_path: C:\\\\etapfiles\\cart_image.jpg
headless_enabled: false